shopping_app/config/routes.rb
Rails.application.routes.draw do

  resources :products

  resources :sessions

  resources :customers do
    resources :delivery_addresses
    resources :shopping_cart_items
    resources :orders do
      resources :order_items
    end
  end
  get 'shopping_cart_items/new'
  get 'shopping_cart_items/show'
  post 'shopping_cart_items/:id/add' => "shopping_cart_items#add_quantity", as: "shopping_cart_item_add"
  post 'shopping_cart_items/:id/reduce' => "shopping_cart_items#reduce_quantity", as: "shopping_cart_item_reduce"
  post 'shopping_cart_items' => "shopping_cart_items#create"
  get 'orders/show'
  get 'welcome/index'
  root 'welcome#index'
end

shopping_app/app/models/shopping_cart_item.rb
class ShoppingCartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :product

  validates_associated :product
  validates :customer_id, presence: true
end

shopping_app/app/controllers/shopping_cart_items_controller.rb
class ShoppingCartItemsController < ApplicationController
  def show
  end

  def create
    selected_product = Product.find_by(id: params[:product_id])

    if @shopping_cart_item = current_customer.shopping_cart_items.find_by(product_id: selected_product)
      @shopping_cart_item.increment(:quantity)
    else
      @shopping_cart_item = current_customer.shopping_cart_items.new

      @shopping_cart_item.product = selected_product
      @shopping_cart_item.quantity = 1
    end

    if @shopping_cart_item.save
      redirect_to shopping_cart_items_show_path
    else
      render 'new'
    end
  end

  def add_quantity
    shopping_cart_item.increment(:quantity)
    shopping_cart_item.save
    redirect_to shopping_cart_items_show_path
  end

  def reduce_quantity
    shopping_cart_item.decrement(:quantity) if shopping_cart_item.quantity > 1
    shopping_cart_item.save
    redirect_to shopping_cart_items_show_path
  end

  def destroy
    @item = current_customer.shopping_cart_items.find_by(id: params[:id])
    @item.destroy
    redirect_to shopping_cart_items_show_path
  end

  private

  def shopping_cart_item
     @shopping_cart_item ||= ShoppingCartItem.find_by(id: params[:id])
  end
end

shopping_app/app/helpers/shopping_cart_items_helper.rb
module ShoppingCartItemsHelper
end

shopping_app/app/views/shopping_cart_items/new.html.erb
<%= @product.name %> | <%= number_to_currency @product.price %>
  <%= form_with(model: [@customer, @customer.shopping_cart_items.build]) do |f| %>
    <%= f.hidden_field :product_id, value: @product.id %>
    <%= f.label :Quantity %>
    <%= f.number_field :quantity %>
    <%= f.submit "Add to Cart" %>
  <% end %>

<%= link_to 'Back', products_path %>

shopping_app/app/views/shopping_cart_items/show.html.erb
<%= render 'products/header' %>
<% if current_customer.shopping_cart_items.any? %>
  <% total = 0 %>
  <% current_customer.shopping_cart_items.each do |item| %>
    <p><strong>Product: </strong>
    <%= item.product.name %></p>

    <p><strong>Price: </strong>
    <%= item.product.price %></p>

    <p><strong>Quantity: </strong>
    <%= item.quantity %>

    <%= link_to "Increment", shopping_cart_item_add_path(id: item), method: :post %>
    <%= link_to "Decrement", shopping_cart_item_reduce_path(id: item), method: :post %></p>
    <p><strong>Total Price: </strong><%= total_price = item.product.price * item.quantity %></p>
    <%= link_to 'Delete Item', [item.customer,item],
                method: :delete,
                data: { confirm: 'Are you sure?' } %></p>
    <% total += total_price %>
  <% end %>
  <p><strong>Total amount: </strong><%= total %></p>
<% else %>
  <p> Your cart is empty! </p>
  <p> Add a Product.. </p>
<% end %>
<%= link_to 'Proceed to checkout', customer_path(current_customer) %>
<%= link_to 'Go to Product List', products_path %>