shopping_app/config/routes.rb
Rails.application.routes.draw do

  resources :products

  resources :sessions

  resources :customers do
    resources :delivery_addresses
    resources :shopping_cart_items
    resources :orders do
      resources :order_items
    end
  end
  get 'shopping_cart_items/new'
  get 'shopping_cart_items/show'
  post 'shopping_cart_items/:id/add' => "shopping_cart_items#add_quantity", as: "shopping_cart_item_add"
  post 'shopping_cart_items/:id/reduce' => "shopping_cart_items#reduce_quantity", as: "shopping_cart_item_reduce"
  post 'shopping_cart_items' => "shopping_cart_items#create"
  get 'orders/show'
  get 'welcome/index'
  root 'welcome#index'
end

shopping_app/app/models/customer.rb
class Customer < ApplicationRecord
  attr_accessor :password, :password_confirmation
  #enum customer_role: [:admin, :customer]

  has_many :delivery_addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :order_items, through: :orders
  has_many :shopping_cart_items, dependent: :destroy
  has_many :products, through: :shopping_cart_items

  validates_associated :delivery_addresses
  validates_associated :orders
  validates_associated :shopping_cart_items

  validates :name, presence: true
  validates :phone_number, presence: true, length: {minimum: 10}
  validates :password, confirmation: true, length: {minimum: 6}, allow_nil: true

  validates_format_of :email, :with => /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  before_save :encrypt_password
  after_save :clear_password

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

  def self.authenticate(username="", login_password="")
    customer = Customer.find_by_name(username)
    if customer && customer.match_password(login_password)
      return customer
    else
      return false
    end
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end
end

shopping_app/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  skip_before_action :authenticate_customer, only: [:new, :create]
  before_action :save_login_state, only: [:new, :create]
  before_action :valid_customer, except: [:index, :show]

  def index
    @customers = Customer.all if is_admin?
  end

  def show
    @customer = Customer.find_by(id: params[:id])
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find_by(id: params[:id])
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      session[:customer_id] = @customer.id
      redirect_to products_path
    else
      render "new"
    end

  end

  def update
    @customer = Customer.find_by(id: params[:id])
    if @customer.update_attributes(customer_params)
      redirect_to customer_path(@customer)
    else
      render "edit"
    end
  end

  def destroy
    @customer = Customer.find_by(id: params[:id])
    @customer.destroy
    redirect_to customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :phone_number, :password, :password_confirmation)
  end

  def valid_customer
    return true if Customer.find_by(id: params[:id]) == current_customer
    flash[:alert] = "You can edit your details only!"
    redirect_to customers_path
  end
end

shopping_app/app/helpers/customers_helper.rb
module CustomersHelper
end

shopping_app/app/views/customers/edit.html.erb
<font size ="4"><p align=right>
  <%= link_to 'Home', welcome_index_path %></p>
<body bgcolor="#99CCCC" text="#003399" vlink="#0066FF">

<div class="Edit_Form">
  <center><h1>Update Details</h1>
  <%= form_with model: @customer do |f| %>
    <p> Username:</br> <%= f.text_field :name%> </p>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Phone Number:</br> <%= f.text_field :phone_number%> </p>
    <%= f.submit :Update %>
  <% end %>

  <% if @customer.errors.any? %>
    <ul class="Edit_Errors">
    <% for message_error in @customer.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %></center>
</div></font>

<center><%= link_to 'Back', customers_path %></center>

shopping_app/app/views/customers/index.html.erb
<body bgcolor="#99CCCC" text="#000000" vlink="#0066FF">

<p align= right>
  <font size= "5" color ="#006600">Hello <%= current_customer.name%></font>
  <%= link_to 'Home', welcome_index_path %>
  <%= link_to 'Logout', session_path(session[:customer_id]),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>
<HR SIZE="7" WIDTH="100%" color="#CC6699">


<h2>List of Customers</h2>

<style>
  table,th {text-align: left;}

  th { background-color: black; color: white; }

</style>

<table style= "width:50%" >
  <tr>
    <th>Name</th>

    <th>Phone Number</th>
  </tr>

  <% @customers.each do |customer| %>
    <tr>
      <td><%= customer.name %></td>

      <td><%= customer.phone_number %></td>

      <td><%= link_to 'Show-details', customer_path(customer) %></td>
      <td>
        <%= link_to 'Edit', edit_customer_path(customer) if customer == current_customer %>
      </td>
      <td><%= link_to 'Destroy', customer_path(customer),
              method: :delete,
              data: { confirm: 'Are you sure?' } if customer == current_customer %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Go to Products Details', products_path if is_admin?%>

shopping_app/app/views/customers/new.html.erb
<font size ="4">

<p align=right>
  <%= link_to 'Home', welcome_index_path %>
</p>
<body bgcolor="#99CCCC" text="#003399" vlink="#0066FF">

<div class="Sign_Form">
  <center><h1>Sign Up</h1>
  <%= form_for(:customer, :url => {:controller => 'customers', :action => 'create'}) do |f| %>
    <p> Username:</br> <%= f.text_field :name%> </p>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Phone Number:</br> <%= f.text_field :phone_number%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup %>
  <% end %>

  <% if @customer.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @customer.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %></center>
</div>
</font>

shopping_app/app/views/customers/show.html.erb
<%= render 'products/header' %>

<p>
  <strong>Customer Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @customer.phone_number %>
</p>

<h4>Delivery Addresses:</h4>
<%= render @customer.delivery_addresses %>

<h4> Add a delivery address: </h4>
<%= render 'delivery_addresses/form' %>

<%= link_to 'Edit Your Details', edit_customer_path(@customer) if @customer == current_customer %>
<p><%= link_to 'Back', customers_path if is_admin? %></p>
<%= link_to 'Back to Product List', products_path %>