shopping_app/config/routes.rb
Rails.application.routes.draw do

  resources :products

  resources :sessions

  resources :customers do
    resources :delivery_addresses
    resources :shopping_cart_items
    resources :orders do
      resources :order_items
    end
  end
  get 'shopping_cart_items/new'
  get 'shopping_cart_items/show'
  post 'shopping_cart_items/:id/add' => "shopping_cart_items#add_quantity", as: "shopping_cart_item_add"
  post 'shopping_cart_items/:id/reduce' => "shopping_cart_items#reduce_quantity", as: "shopping_cart_item_reduce"
  post 'shopping_cart_items' => "shopping_cart_items#create"
  get 'orders/show'
  get 'welcome/index'
  root 'welcome#index'
end

shopping_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_customer, only: [:index]
  def index
  end
end

shopping_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

shopping_app/app/views/welcome/index.html.erb
<body bgcolor="#99CCCC" text="#006600" vlink="#0066FF">

<p align=right>© <%= Date.today.year %> </p>


<HR SIZE="7" WIDTH="100%" color="#CC6699">

<p align=right>
  <%= link_to 'SignUp', new_customer_path %>
  <%= link_to 'Login', new_session_path %>
</p>

<font size = "15"><Strong><center>Welcome!</center></Strong></font>
<font size = "30" color="#CC6699"><h1><center><I>My Shopping App</I></center></h1></font>

<p>
  <h2><center>Login to Enjoy Shopping...</center></h2>
</p>
<p>
  <h3><center><%= link_to 'Take a look at website', products_path %></center></h3>
</p>