shopping_app/config/routes.rb
Rails.application.routes.draw do

  resources :products

  resources :sessions

  resources :customers do
    resources :delivery_addresses
    resources :shopping_cart_items
    resources :orders do
      resources :order_items
    end
  end
  get 'shopping_cart_items/new'
  get 'shopping_cart_items/show'
  post 'shopping_cart_items/:id/add' => "shopping_cart_items#add_quantity", as: "shopping_cart_item_add"
  post 'shopping_cart_items/:id/reduce' => "shopping_cart_items#reduce_quantity", as: "shopping_cart_item_reduce"
  post 'shopping_cart_items' => "shopping_cart_items#create"
  get 'orders/show'
  get 'welcome/index'
  root 'welcome#index'
end

shopping_app/app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
  has_many :shopping_cart_items
  has_attached_file :image, styles: { thumb: ["64x64#", :jpg],
                            original: ['500x500>', :jpg] },
                  convert_options: { thumb: "-quality 75 -strip",
                                     original: "-quality 85 -strip" }

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true

  validates_attachment :image,
                     content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
                      size: { in: 0..500.kilobytes }

end

shopping_app/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :authenticate_customer, only: [:index, :show]
  before_action :check_admin, except: [:index, :show]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find_by(id: params[:id])
  end

  def new
    @product = Product.new

  end

  def edit
    @product = Product.find_by(id: params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def update
    @product = Product.find_by(id: params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find_by(id: params[:id])
    @product.destroy
    redirect_to products_path
  end

  private
  def product_params
    params.require(:product).permit(:image, :name, :description, :price, :stock_quantity)
  end

  def check_admin
    return true if is_admin?
    redirect_to root_url
  end
end

shopping_app/app/helpers/products_helper.rb
module ProductsHelper
end

shopping_app/app/views/products/_form.html.erb
<%= form_with model: @product, local: true  do |form| %>
  <p>
    <%= form.label :Product %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :Description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :Price %><br>
    <%= form.text_field :price %>
  </p>

  <p>
    <%= form.label :image %>
    <%= form.file_field :image%>
  </p>

  <p>
    <%= form.label "Qunatity in stock" %><br>
    <%= form.text_field :stock_quantity %>
  </p>

  <p>
    <%= form.submit  %>
  </p>

<% end %>

shopping_app/app/views/products/_header.html.erb
<body bgcolor="#99CCCC" text="#000000" vlink="#0066FF">
<p align= right>
  <font size= "5" color ="#006600">Hello <%=current_customer.name if current_customer%>!!</font>
  <%= link_to 'Your Details', customer_path(current_customer) if current_customer%>
  <%= link_to 'Cart', shopping_cart_items_show_path if current_customer%>
  <%= link_to 'Orders', orders_show_path if current_customer%>
  <%= link_to 'Home', welcome_index_path %>
  <%= link_to 'Logout', session_path(session[:customer_id]),
              method: :delete,
              data: { confirm: 'Are you sure?' } if current_customer%>
</p>
<HR SIZE="7" WIDTH="100%" color="#CC6699">

shopping_app/app/views/products/_photo.html.erb
<div class="media">
  <div class="media-left">
    <%= link_to image_tag(@product.image.url, class: 'media-object'), @product.image.url, target: '_blank' %>
  </div>
  <div class="media-body">
    <h4 class="media-heading"><%= @product.name %></h4>
  </div>
</div>
<%= link_to image_tag(@product.image.url(:thumb), class: 'media-object'), @product.image.url, target: '_blank' %>

shopping_app/app/views/products/edit.html.erb
<%= render 'header' %>
<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

shopping_app/app/views/products/index.html.erb
<%= render 'header' %>


<h2>List of Products</h2>
<%= if is_admin?
      link_to 'New product', new_product_path
    end%>

<style>
table,th {text-align: left;}

th { background-color: black; color: white; }

</style>

<table style= "width:60%" >
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Image</th>
  </tr>

  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>

      <td><%= product.price %></td>
      <td><%= link_to image_tag(product.image.url(:thumb)), product.image.url, target: '_blank' %></td>

      <td><% if product.stock_quantity != 0 %>
                <%= link_to 'Add to Cart', shopping_cart_items_path(product_id: product.id), method: :post if current_customer %>
          <% else %>
                <strong>Out of stock!!</strong>
          <% end %></td>

      <td><%= link_to 'Show-details', product_path(product) %>
          <%= link_to 'Edit', edit_product_path(product) if is_admin? %>
          <%= link_to 'Destroy', product_path(product),
                       method: :delete,
                       data: { confirm: 'Are you sure?' } if is_admin?%></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Go to Customers Details', customers_path if is_admin? %>

shopping_app/app/views/products/new.html.erb
<%= render 'header' %>

<h1>New Product</h1>

<%= render "form" %>

<p><%= if is_admin?
     link_to 'Add more products', new_product_path
    end
%></p>
<%= link_to 'Back', products_path %>

shopping_app/app/views/products/show.html.erb
<%= render 'header' %>

<p>
  <strong>Product Name: </strong>
  <%= @product.name %>
</p>

<%= link_to image_tag(@product.image.url), @product.image.url, target: '_blank' %>

<p>
  <strong>Description: </strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price: </strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity in stock:</strong>
  <%= @product.stock_quantity %>
</p>

<%= if is_admin?
      link_to 'Edit', edit_product_path(@product)
    end%>
<%= link_to 'Back', products_path %>
<%=link_to 'Add to Cart', shopping_cart_items_path(product_id: @product.id), method: :post if current_customer && @product.stock_quantity != 0 %></td>